import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1770035645312 implements MigrationInterface {
    name = 'Migrations1770035645312'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "location_address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying(255), "city" character varying(255), "state" character varying(255), "zip" character varying(255), "country" character varying(255), "timezone" character varying(255), "location_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_3191fd40b5538e1e5c3857042f" UNIQUE ("location_id"), CONSTRAINT "PK_bf1188fd425a5c4f19d6fa22c2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."location_working_hours_day_enum" AS ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')`);
        await queryRunner.query(`CREATE TABLE "location_working_hours" ("id" SERIAL NOT NULL, "location_id" uuid NOT NULL, "day" "public"."location_working_hours_day_enum" NOT NULL, "open" TIME NOT NULL, "close" TIME NOT NULL, "breaks" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_142ac264c09dd3d555a1e73f0e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c180c8aef03938b9a3470d398f" ON "location_working_hours" ("location_id", "day") `);
        await queryRunner.query(`CREATE TABLE "company_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "service_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d22c61d4d1d9642de3466530279" UNIQUE ("company_id", "service_id"), CONSTRAINT "PK_25fc94c7e4cfcf84d772c76c68e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "base_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "specialization_id" uuid NOT NULL, "trade_id" integer NOT NULL, "duration_minutes" integer NOT NULL, "required_staff" integer NOT NULL DEFAULT '1', "buffer_minutes" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "archived" boolean NOT NULL DEFAULT false, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_9bd31e77f521545ccccc79b0787" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "base_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "trade_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1344f44856f7b6afd09e930b350" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trade_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_72184e1f37f832e903d2dc0d868" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9156af13862cf05a303701a72f" ON "trade_groups" ("name") `);
        await queryRunner.query(`CREATE TABLE "trade" ("id" SERIAL NOT NULL, "group_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "user_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d4097908741dc408f8274ebdc53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_251a1a9999d8f1d33f1fa15698" ON "trade" ("group_id") `);
        await queryRunner.query(`CREATE TYPE "public"."location_status_enum" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`CREATE TABLE "location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "status" "public"."location_status_enum" NOT NULL DEFAULT '1', "is_primary" boolean NOT NULL DEFAULT false, "type" character varying(20), "company_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_876d7bdba03c72251ec4c2dc827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_address" ("company_id" uuid NOT NULL, "line1" character varying(255), "line2" character varying(255), "city" character varying(100), "state" character varying(50), "postal_code" character varying(20), "country" character(2) DEFAULT 'US', CONSTRAINT "PK_94eab1f5f65b2c641c0b5c4a067" PRIMARY KEY ("company_id"))`);
        await queryRunner.query(`CREATE TABLE "media" ("id" SERIAL NOT NULL, "filename" character varying(255) NOT NULL, "file_path" character varying(1024), "url" character varying(1024) NOT NULL, "owner_type" character varying(200), "owner_id" character varying(200), "collection" character varying(200) NOT NULL DEFAULT 'default', "position" integer NOT NULL DEFAULT '0', "metadata_json" jsonb, "file_format" character varying(50) NOT NULL, "file_size_kb" double precision NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "UQ_abc159b084b9d36de6bcabbfb82" UNIQUE ("filename"), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abc159b084b9d36de6bcabbfb8" ON "media" ("filename") `);
        await queryRunner.query(`CREATE TABLE "addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "detailed_description" text, "best_for" text, "benefits" jsonb, "slug" character varying(200) NOT NULL, "price_cents" bigint NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'USD', "stripe_product_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cd49fb3dc0558f02cb6fe6cc138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf6897b3f7b2e6b712bdf01f29" ON "addons" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_359f971aa4b0ae502460f822ca" ON "addons" ("slug") `);
        await queryRunner.query(`CREATE TABLE "company_addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "addon_id" uuid NOT NULL, "stripe_subscription_item_id" character varying(255), "stripe_product_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_29e0a7b3ac8b2f6829e7b62104b" UNIQUE ("company_id", "addon_id"), CONSTRAINT "PK_98e11b718f2f3ceca57eabc1cb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."companies_entity_type_enum" AS ENUM('LLC', 'C_CORP', 'S_CORP', 'SOLE_PROP', 'PARTNERSHIP')`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255), "subdomain" character varying(255), "country" character varying(100), "email" character varying(255), "phone" character varying(255), "timezone" character varying(50), "legal_name" character varying(255), "dba_name" character varying(255), "entity_type" "public"."companies_entity_type_enum", "registration_number" character varying(100), "ein" character varying(10), "stripe_customer_id" character varying, "has_schedule" boolean NOT NULL DEFAULT false, "has_education" boolean NOT NULL DEFAULT false, "has_products" boolean NOT NULL DEFAULT false, "template_id" uuid, "color_palette_id" uuid, "font_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_665e863569cb7332e624dc88c8c" UNIQUE ("subdomain"), CONSTRAINT "UQ_d0af6f5866201d5cb424767744a" UNIQUE ("email"), CONSTRAINT "UQ_d477050c058ca769d3808caef51" UNIQUE ("phone"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "onboardings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "company_id" uuid, "current_step" integer NOT NULL DEFAULT '1', "completed" boolean NOT NULL DEFAULT false, "steps_data" jsonb, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f062ffd56f2690a957e54bab976" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "password_hash" character varying(255) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'admin', "company_id" uuid, "location_id" uuid, "status" "public"."users_status_enum" NOT NULL DEFAULT '0', "tfa_mode" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_form" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "form_template_version_id" uuid NOT NULL, "name" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_6f2dba72560eb98ab6416a5c2cc" UNIQUE ("business_id", "form_template_version_id"), CONSTRAINT "PK_892cca58aead301adb85fad51a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_form_field" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_form_id" uuid NOT NULL, "form_field_id" uuid NOT NULL, "label_override" character varying(255), "is_required_override" boolean, "is_hidden" boolean NOT NULL DEFAULT false, "sort_order" integer, "settings_override" jsonb, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_2347316e290ae32dd59411f406e" UNIQUE ("business_form_id", "form_field_id"), CONSTRAINT "PK_a5bf967cf822286f085aecee1ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_field" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_template_version_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "label" character varying(255) NOT NULL, "field_type" character varying(50) NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "placeholder" character varying(255), "help_text" text, "sort_order" integer NOT NULL DEFAULT '0', "settings" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_a4b69255607549730e15026cce0" UNIQUE ("form_template_version_id", "name"), CONSTRAINT "PK_135904ddb60085b07254ea4f485" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_template_version" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_template_id" uuid NOT NULL, "version" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_68aac59b0dcd48c8565a351cc76" UNIQUE ("form_template_id", "version"), CONSTRAINT "PK_90b8777c2a85638529c87050b2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "trade_id" integer NOT NULL, "business_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_656844082de48d37a2c8fb7cfdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_tokens" ("id" SERIAL NOT NULL, "user_id" uuid NOT NULL, "token" character varying(500) NOT NULL, "type" character varying(20) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "device_type" character varying(50), "ip_address" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63764db9d9aaa4af33e07b2f4bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_resets" ("id" SERIAL NOT NULL, "user_id" uuid NOT NULL, "token" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b34edd5264effbbc875c266a9e" UNIQUE ("token"), CONSTRAINT "PK_4816377aa98211c1de34469e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "verification_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "code" character varying(10) NOT NULL, "method" character varying(10) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18741b6b8bf1680dbf5057421d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "base_specialization_id" uuid, "name" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "archived" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7897ed818949395f7f82465c76e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "base_service_id" uuid, "name" character varying(255) NOT NULL, "duration_minutes" integer, "required_staff" integer, "buffer_minutes" integer, "price" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "archived" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4b6dd7a4ce2532b6ad960b3d537" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."company_notification_templates_provider_enum" AS ENUM('email', 'sms', 'push')`);
        await queryRunner.query(`CREATE TABLE "company_notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "provider" "public"."company_notification_templates_provider_enum" NOT NULL DEFAULT 'email', "title" text, "body" text NOT NULL, "base_template_id" uuid NOT NULL, "created_by" uuid, "last_sync_date" TIMESTAMP NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "type_id" uuid, CONSTRAINT "PK_34453745bb0f3813b43092d860e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3829ae1a6554108530f1b56d74" ON "company_notification_templates" ("company_id", "type_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36303b1a357c0ce359ea820dc6" ON "company_notification_templates" ("company_id", "base_template_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_provider_enum" AS ENUM('email', 'sms', 'push')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "provider" "public"."notification_templates_provider_enum" NOT NULL DEFAULT 'email', "title" text NOT NULL, "body" text NOT NULL, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_33865415e76edbac9a8d01cd62" ON "notification_templates" ("type_id") `);
        await queryRunner.query(`CREATE TABLE "notification_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(120) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_58e4a26add3dbc104fc9265d5ae" UNIQUE ("key"), CONSTRAINT "PK_aa965e094494e2c4c5942cfb42d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_58e4a26add3dbc104fc9265d5a" ON "notification_types" ("key") `);
        await queryRunner.query(`CREATE TABLE "notification_variables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(120) NOT NULL, "label" character varying(255), "description" text, "required" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1185488f00366cd8765464dc6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_notification_masters_digest_frequency_enum" AS ENUM('off', 'hourly', 'daily', 'weekly')`);
        await queryRunner.query(`CREATE TABLE "user_notification_masters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "digest_frequency" "public"."user_notification_masters_digest_frequency_enum" NOT NULL DEFAULT 'off', "quiet_hours" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7d699e517552244cc66b5d8cf2f" UNIQUE ("user_id"), CONSTRAINT "REL_7d699e517552244cc66b5d8cf2" UNIQUE ("user_id"), CONSTRAINT "PK_4e304151bda3f417a413f8bf5cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d699e517552244cc66b5d8cf2" ON "user_notification_masters" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "notification_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(150) NOT NULL, "description" text, CONSTRAINT "PK_b90ee23556ab9be494461474417" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "alias" character varying(150) NOT NULL, "description" text, CONSTRAINT "UQ_5693d80bea1da6676b9e3bfcbb2" UNIQUE ("alias"), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5693d80bea1da6676b9e3bfcbb" ON "notifications" ("alias") `);
        await queryRunner.query(`CREATE TABLE "user_notification_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "notification_id" uuid NOT NULL, "email" boolean NOT NULL DEFAULT true, "phone" boolean NOT NULL DEFAULT true, "push" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6d43a06c9b2becbeb85f702e8ae" UNIQUE ("user_id", "notification_id"), CONSTRAINT "PK_a195de67d093e096152f387afbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52182ffd0f785e8256f8fcb4fd" ON "user_notification_settings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c22ea24c9102612ef3ce0a514" ON "user_notification_settings" ("notification_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying(10) NOT NULL, "entity_type" character varying(255) NOT NULL, "entity_id" text, "company_id" uuid, "location_id" uuid, "user_id" uuid, "request_method" character varying(10), "request_url" text, "request_ip" character varying(64), "request_user_agent" text, "correlation_id" character varying(128), "change_patch" jsonb, "snapshot_before" jsonb, "snapshot_after" jsonb, "meta" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mobile_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" character varying(64) NOT NULL, "release_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_force" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "PK_531e336e682be549bc4727db5f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_008e5f82d7cdb02a922d084ce0" ON "mobile_versions" ("version") `);
        await queryRunner.query(`CREATE TABLE "company_payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "stripe_payment_method_id" character varying(255) NOT NULL, "type" character varying(50) NOT NULL, "last4" character varying(10), "brand" character varying(50), "exp_month" integer, "exp_year" integer, "billing_name" character varying(255), "is_primary" boolean NOT NULL DEFAULT false, "fingerprint" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7f9233e77d51ef422b9c7430f6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0da475b0e73636fc00340d4aab" ON "company_payment_methods" ("company_id") `);
        await queryRunner.query(`CREATE TYPE "public"."company_subscriptions_status_enum" AS ENUM('active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'trialing', 'unpaid', 'expired')`);
        await queryRunner.query(`CREATE TABLE "company_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "stripe_customer_id" character varying(255), "stripe_subscription_id" character varying(255), "stripe_price_id" character varying(255), "plan_id" uuid, "price_id" uuid, "plan_snapshot" jsonb, "addons_snapshot" jsonb, "addon_ids" jsonb, "max_users" integer, "status" "public"."company_subscriptions_status_enum", "current_period_start" TIMESTAMP WITH TIME ZONE, "current_period_end" TIMESTAMP WITH TIME ZONE, "subscription_expires_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2dad37af4a389c2878c9b67a050" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0aa4c0ffc36ddb76fee4e05ea4" ON "company_subscriptions" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "subscription_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_subscription_id" uuid NOT NULL, "period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "amount_cents" bigint, "currency" character varying(50), "invoice_id" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f9830636d998675cb1890b2e4b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d15821ae4d82451b0b2d56ca51" ON "subscription_periods" ("company_subscription_id") `);
        await queryRunner.query(`CREATE TABLE "stripe_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stripe_event_id" character varying(255), "stripe_object_id" character varying(255), "type" character varying(100), "company_id" integer, "company_subscription_id" uuid, "amount_cents" bigint, "currency" character varying(10), "status" character varying(50), "raw" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e6a09f62ba9944f59cfadb066fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc424589c8c931d22609631928" ON "stripe_transactions" ("stripe_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4027ee36987e249f647e9b90e5" ON "stripe_transactions" ("stripe_object_id") `);
        await queryRunner.query(`CREATE TABLE "onboarding_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "onboarding_id" uuid NOT NULL, "key" character varying(200) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "progress" integer NOT NULL DEFAULT '0', "meta" jsonb, "message" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_04ddbad3ed27e955e9edd674447" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3e447b137cdbd15d043c0cb37" ON "onboarding_tasks" ("onboarding_id") `);
        await queryRunner.query(`CREATE TABLE "tiers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "max_users" integer, "max_locations" integer, "benefits" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_908405492b9b2c2ae1cea1e1cc0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97de08a14957cf04f6c075a439" ON "tiers" ("key") `);
        await queryRunner.query(`CREATE TABLE "plan_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_option_id" uuid NOT NULL, "interval" character varying(20) NOT NULL, "price_cents" bigint NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "stripe_price_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_69b05dce9891d42a3d0fc77eec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca11fa664eb5d280503e99fd90" ON "plan_prices" ("interval") `);
        await queryRunner.query(`CREATE TABLE "plan_option_addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_option_id" uuid NOT NULL, "addon_id" uuid NOT NULL, "included" boolean NOT NULL DEFAULT false, "price_cents" bigint, "currency" character varying(10), "stripe_price_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_32fbd6c29361d689c8b20b0e115" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c46a096413d2328ab8349a7f34" ON "plan_option_addons" ("plan_option_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc2e95650801ed8ba380a1fae" ON "plan_option_addons" ("addon_id") `);
        await queryRunner.query(`CREATE TABLE "plan_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tier_id" uuid NOT NULL, "key" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "benefits" jsonb, "extra_practitioner_price_cents" bigint, "website_included" boolean NOT NULL DEFAULT false, "website_price_monthly_cents" bigint, "website_price_yearly_cents" bigint, "educator_upgrade_monthly_cents" bigint, "stripe_product_id" character varying(255), "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5abd14de12b75bf71f25df5762d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c172a1b247ee508654335e88f9" ON "plan_options" ("key") `);
        await queryRunner.query(`CREATE TABLE "location_trades" ("location_id" uuid NOT NULL, "trade_id" integer NOT NULL, CONSTRAINT "PK_d0aba48fb66ebdb06cc46333580" PRIMARY KEY ("location_id", "trade_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d1bd21126aa8aac6c51586ed9" ON "location_trades" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e1107b41d8459796459f0028e" ON "location_trades" ("trade_id") `);
        await queryRunner.query(`CREATE TABLE "company_trades" ("company_id" uuid NOT NULL, "trade_id" integer NOT NULL, CONSTRAINT "PK_3b8ebf881bb80c49a0f15f298fa" PRIMARY KEY ("company_id", "trade_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a59446f122d5cf47b8d7d3333f" ON "company_trades" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aff385b72276c65176b2948080" ON "company_trades" ("trade_id") `);
        await queryRunner.query(`CREATE TABLE "notification_type_variables" ("notification_type_id" uuid NOT NULL, "notification_variable_id" uuid NOT NULL, CONSTRAINT "PK_528b115fabb4757b1182c0cb6e4" PRIMARY KEY ("notification_type_id", "notification_variable_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_151184a011522ec12625c5e8a5" ON "notification_type_variables" ("notification_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b6dbfbba90c40e69769583279" ON "notification_type_variables" ("notification_variable_id") `);
        await queryRunner.query(`ALTER TABLE "location_address" ADD CONSTRAINT "FK_3191fd40b5538e1e5c3857042f2" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_working_hours" ADD CONSTRAINT "FK_e7706e6466c3c43a0b450c5220b" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD CONSTRAINT "FK_b5571c5712b23fe34e7e7dda8ed" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD CONSTRAINT "FK_dbff882850c0db7ac4198292101" FOREIGN KEY ("service_id") REFERENCES "base_services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "base_services" ADD CONSTRAINT "FK_e889f6f42db148a2ba816e17cf8" FOREIGN KEY ("specialization_id") REFERENCES "base_specializations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "base_services" ADD CONSTRAINT "FK_4b8cb1f5ea7940b09668a502533" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "base_services" ADD CONSTRAINT "FK_33204a5591cc10d7161338db880" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "base_specializations" ADD CONSTRAINT "FK_898da00e075d8585893318a8381" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade" ADD CONSTRAINT "FK_251a1a9999d8f1d33f1fa156986" FOREIGN KEY ("group_id") REFERENCES "trade_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade" ADD CONSTRAINT "FK_ac40608b8665839bcbb69ab510d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_e4417d8dfc1bbe1edb0776848d4" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_address" ADD CONSTRAINT "FK_94eab1f5f65b2c641c0b5c4a067" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_addons" ADD CONSTRAINT "FK_875f5aa6a375fe36eb81d13db78" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_addons" ADD CONSTRAINT "FK_307839ca0067013d8b46b0f1d10" FOREIGN KEY ("addon_id") REFERENCES "addons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboardings" ADD CONSTRAINT "FK_e7d7cf95bb620a30d79383490d2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_7ae6334059289559722437bcc1c" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1523fb2aebce55b9e820122ee0e" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_form" ADD CONSTRAINT "FK_d857f90e526082ca2d869820d9f" FOREIGN KEY ("business_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_form" ADD CONSTRAINT "FK_07789eac8a596d23ca6bfa0d2da" FOREIGN KEY ("form_template_version_id") REFERENCES "form_template_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_form_field" ADD CONSTRAINT "FK_2b87905a4cb98ba58992b348cf5" FOREIGN KEY ("business_form_id") REFERENCES "business_form"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_form_field" ADD CONSTRAINT "FK_4e43d67fc8fe57c87486d548ded" FOREIGN KEY ("form_field_id") REFERENCES "form_field"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD CONSTRAINT "FK_b7e8b0a442fbeb62b0ee28a8470" FOREIGN KEY ("form_template_version_id") REFERENCES "form_template_version"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_version" ADD CONSTRAINT "FK_74b38c23fd562d28645c09d5a8a" FOREIGN KEY ("form_template_id") REFERENCES "form_template"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_version" ADD CONSTRAINT "FK_63093cec6ddb9e53a637ec8f1d4" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "FK_98f179efa35b6fb87943f991ea8" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "FK_d812567ae7cd5167295d974078a" FOREIGN KEY ("business_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template" ADD CONSTRAINT "FK_63d503f239df51aed2908a5777f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_tokens" ADD CONSTRAINT "FK_9e144a67be49e5bba91195ef5de" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "FK_f7a4c3bc48f24df007936d217be" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_codes" ADD CONSTRAINT "FK_0a53c41a810420ee446082ce6c6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_specializations" ADD CONSTRAINT "FK_9e3b546f44a9c605057396653be" FOREIGN KEY ("business_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_specializations" ADD CONSTRAINT "FK_0a0580b7b06a29dbfc4c660766a" FOREIGN KEY ("base_specialization_id") REFERENCES "base_specializations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_services" ADD CONSTRAINT "FK_11a5e9c875104b1de2461018b63" FOREIGN KEY ("business_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_services" ADD CONSTRAINT "FK_d4ea0841d4183cd59fe1cf03e2c" FOREIGN KEY ("base_service_id") REFERENCES "base_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_notification_templates" ADD CONSTRAINT "FK_25335973ba8d51ff94d4aeaa558" FOREIGN KEY ("type_id") REFERENCES "notification_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_notification_templates" ADD CONSTRAINT "FK_ee736fb5a8549bf708336429da3" FOREIGN KEY ("base_template_id") REFERENCES "notification_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_templates" ADD CONSTRAINT "FK_33865415e76edbac9a8d01cd625" FOREIGN KEY ("type_id") REFERENCES "notification_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_masters" ADD CONSTRAINT "FK_7d699e517552244cc66b5d8cf2f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_aadebe51dd06bd1e35bf6504ff5" FOREIGN KEY ("category_id") REFERENCES "notification_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD CONSTRAINT "FK_52182ffd0f785e8256f8fcb4fd6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" ADD CONSTRAINT "FK_7c22ea24c9102612ef3ce0a5140" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_payment_methods" ADD CONSTRAINT "FK_0da475b0e73636fc00340d4aab5" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_subscriptions" ADD CONSTRAINT "FK_0aa4c0ffc36ddb76fee4e05ea4b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_periods" ADD CONSTRAINT "FK_d15821ae4d82451b0b2d56ca516" FOREIGN KEY ("company_subscription_id") REFERENCES "company_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_prices" ADD CONSTRAINT "FK_3802eb5719d6cc32a2308b3c8db" FOREIGN KEY ("plan_option_id") REFERENCES "plan_options"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_option_addons" ADD CONSTRAINT "FK_c46a096413d2328ab8349a7f345" FOREIGN KEY ("plan_option_id") REFERENCES "plan_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_option_addons" ADD CONSTRAINT "FK_bdc2e95650801ed8ba380a1fae4" FOREIGN KEY ("addon_id") REFERENCES "addons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_options" ADD CONSTRAINT "FK_c8b58fc4464d360ffd38702b489" FOREIGN KEY ("tier_id") REFERENCES "tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_trades" ADD CONSTRAINT "FK_6d1bd21126aa8aac6c51586ed95" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "location_trades" ADD CONSTRAINT "FK_4e1107b41d8459796459f0028e0" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "company_trades" ADD CONSTRAINT "FK_a59446f122d5cf47b8d7d3333f5" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "company_trades" ADD CONSTRAINT "FK_aff385b72276c65176b29480806" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_type_variables" ADD CONSTRAINT "FK_151184a011522ec12625c5e8a58" FOREIGN KEY ("notification_type_id") REFERENCES "notification_types"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_type_variables" ADD CONSTRAINT "FK_1b6dbfbba90c40e697695832795" FOREIGN KEY ("notification_variable_id") REFERENCES "notification_variables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification_type_variables" DROP CONSTRAINT "FK_1b6dbfbba90c40e697695832795"`);
        await queryRunner.query(`ALTER TABLE "notification_type_variables" DROP CONSTRAINT "FK_151184a011522ec12625c5e8a58"`);
        await queryRunner.query(`ALTER TABLE "company_trades" DROP CONSTRAINT "FK_aff385b72276c65176b29480806"`);
        await queryRunner.query(`ALTER TABLE "company_trades" DROP CONSTRAINT "FK_a59446f122d5cf47b8d7d3333f5"`);
        await queryRunner.query(`ALTER TABLE "location_trades" DROP CONSTRAINT "FK_4e1107b41d8459796459f0028e0"`);
        await queryRunner.query(`ALTER TABLE "location_trades" DROP CONSTRAINT "FK_6d1bd21126aa8aac6c51586ed95"`);
        await queryRunner.query(`ALTER TABLE "plan_options" DROP CONSTRAINT "FK_c8b58fc4464d360ffd38702b489"`);
        await queryRunner.query(`ALTER TABLE "plan_option_addons" DROP CONSTRAINT "FK_bdc2e95650801ed8ba380a1fae4"`);
        await queryRunner.query(`ALTER TABLE "plan_option_addons" DROP CONSTRAINT "FK_c46a096413d2328ab8349a7f345"`);
        await queryRunner.query(`ALTER TABLE "plan_prices" DROP CONSTRAINT "FK_3802eb5719d6cc32a2308b3c8db"`);
        await queryRunner.query(`ALTER TABLE "subscription_periods" DROP CONSTRAINT "FK_d15821ae4d82451b0b2d56ca516"`);
        await queryRunner.query(`ALTER TABLE "company_subscriptions" DROP CONSTRAINT "FK_0aa4c0ffc36ddb76fee4e05ea4b"`);
        await queryRunner.query(`ALTER TABLE "company_payment_methods" DROP CONSTRAINT "FK_0da475b0e73636fc00340d4aab5"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP CONSTRAINT "FK_7c22ea24c9102612ef3ce0a5140"`);
        await queryRunner.query(`ALTER TABLE "user_notification_settings" DROP CONSTRAINT "FK_52182ffd0f785e8256f8fcb4fd6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_aadebe51dd06bd1e35bf6504ff5"`);
        await queryRunner.query(`ALTER TABLE "user_notification_masters" DROP CONSTRAINT "FK_7d699e517552244cc66b5d8cf2f"`);
        await queryRunner.query(`ALTER TABLE "notification_templates" DROP CONSTRAINT "FK_33865415e76edbac9a8d01cd625"`);
        await queryRunner.query(`ALTER TABLE "company_notification_templates" DROP CONSTRAINT "FK_ee736fb5a8549bf708336429da3"`);
        await queryRunner.query(`ALTER TABLE "company_notification_templates" DROP CONSTRAINT "FK_25335973ba8d51ff94d4aeaa558"`);
        await queryRunner.query(`ALTER TABLE "business_services" DROP CONSTRAINT "FK_d4ea0841d4183cd59fe1cf03e2c"`);
        await queryRunner.query(`ALTER TABLE "business_services" DROP CONSTRAINT "FK_11a5e9c875104b1de2461018b63"`);
        await queryRunner.query(`ALTER TABLE "business_specializations" DROP CONSTRAINT "FK_0a0580b7b06a29dbfc4c660766a"`);
        await queryRunner.query(`ALTER TABLE "business_specializations" DROP CONSTRAINT "FK_9e3b546f44a9c605057396653be"`);
        await queryRunner.query(`ALTER TABLE "verification_codes" DROP CONSTRAINT "FK_0a53c41a810420ee446082ce6c6"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT "FK_f7a4c3bc48f24df007936d217be"`);
        await queryRunner.query(`ALTER TABLE "user_tokens" DROP CONSTRAINT "FK_9e144a67be49e5bba91195ef5de"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "FK_63d503f239df51aed2908a5777f"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "FK_d812567ae7cd5167295d974078a"`);
        await queryRunner.query(`ALTER TABLE "form_template" DROP CONSTRAINT "FK_98f179efa35b6fb87943f991ea8"`);
        await queryRunner.query(`ALTER TABLE "form_template_version" DROP CONSTRAINT "FK_63093cec6ddb9e53a637ec8f1d4"`);
        await queryRunner.query(`ALTER TABLE "form_template_version" DROP CONSTRAINT "FK_74b38c23fd562d28645c09d5a8a"`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP CONSTRAINT "FK_b7e8b0a442fbeb62b0ee28a8470"`);
        await queryRunner.query(`ALTER TABLE "business_form_field" DROP CONSTRAINT "FK_4e43d67fc8fe57c87486d548ded"`);
        await queryRunner.query(`ALTER TABLE "business_form_field" DROP CONSTRAINT "FK_2b87905a4cb98ba58992b348cf5"`);
        await queryRunner.query(`ALTER TABLE "business_form" DROP CONSTRAINT "FK_07789eac8a596d23ca6bfa0d2da"`);
        await queryRunner.query(`ALTER TABLE "business_form" DROP CONSTRAINT "FK_d857f90e526082ca2d869820d9f"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1523fb2aebce55b9e820122ee0e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_7ae6334059289559722437bcc1c"`);
        await queryRunner.query(`ALTER TABLE "onboardings" DROP CONSTRAINT "FK_e7d7cf95bb620a30d79383490d2"`);
        await queryRunner.query(`ALTER TABLE "company_addons" DROP CONSTRAINT "FK_307839ca0067013d8b46b0f1d10"`);
        await queryRunner.query(`ALTER TABLE "company_addons" DROP CONSTRAINT "FK_875f5aa6a375fe36eb81d13db78"`);
        await queryRunner.query(`ALTER TABLE "company_address" DROP CONSTRAINT "FK_94eab1f5f65b2c641c0b5c4a067"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_e4417d8dfc1bbe1edb0776848d4"`);
        await queryRunner.query(`ALTER TABLE "trade" DROP CONSTRAINT "FK_ac40608b8665839bcbb69ab510d"`);
        await queryRunner.query(`ALTER TABLE "trade" DROP CONSTRAINT "FK_251a1a9999d8f1d33f1fa156986"`);
        await queryRunner.query(`ALTER TABLE "base_specializations" DROP CONSTRAINT "FK_898da00e075d8585893318a8381"`);
        await queryRunner.query(`ALTER TABLE "base_services" DROP CONSTRAINT "FK_33204a5591cc10d7161338db880"`);
        await queryRunner.query(`ALTER TABLE "base_services" DROP CONSTRAINT "FK_4b8cb1f5ea7940b09668a502533"`);
        await queryRunner.query(`ALTER TABLE "base_services" DROP CONSTRAINT "FK_e889f6f42db148a2ba816e17cf8"`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP CONSTRAINT "FK_dbff882850c0db7ac4198292101"`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP CONSTRAINT "FK_b5571c5712b23fe34e7e7dda8ed"`);
        await queryRunner.query(`ALTER TABLE "location_working_hours" DROP CONSTRAINT "FK_e7706e6466c3c43a0b450c5220b"`);
        await queryRunner.query(`ALTER TABLE "location_address" DROP CONSTRAINT "FK_3191fd40b5538e1e5c3857042f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b6dbfbba90c40e69769583279"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151184a011522ec12625c5e8a5"`);
        await queryRunner.query(`DROP TABLE "notification_type_variables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aff385b72276c65176b2948080"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a59446f122d5cf47b8d7d3333f"`);
        await queryRunner.query(`DROP TABLE "company_trades"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e1107b41d8459796459f0028e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d1bd21126aa8aac6c51586ed9"`);
        await queryRunner.query(`DROP TABLE "location_trades"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c172a1b247ee508654335e88f9"`);
        await queryRunner.query(`DROP TABLE "plan_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdc2e95650801ed8ba380a1fae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46a096413d2328ab8349a7f34"`);
        await queryRunner.query(`DROP TABLE "plan_option_addons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca11fa664eb5d280503e99fd90"`);
        await queryRunner.query(`DROP TABLE "plan_prices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97de08a14957cf04f6c075a439"`);
        await queryRunner.query(`DROP TABLE "tiers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3e447b137cdbd15d043c0cb37"`);
        await queryRunner.query(`DROP TABLE "onboarding_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4027ee36987e249f647e9b90e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc424589c8c931d22609631928"`);
        await queryRunner.query(`DROP TABLE "stripe_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d15821ae4d82451b0b2d56ca51"`);
        await queryRunner.query(`DROP TABLE "subscription_periods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0aa4c0ffc36ddb76fee4e05ea4"`);
        await queryRunner.query(`DROP TABLE "company_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."company_subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0da475b0e73636fc00340d4aab"`);
        await queryRunner.query(`DROP TABLE "company_payment_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_008e5f82d7cdb02a922d084ce0"`);
        await queryRunner.query(`DROP TABLE "mobile_versions"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c22ea24c9102612ef3ce0a514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52182ffd0f785e8256f8fcb4fd"`);
        await queryRunner.query(`DROP TABLE "user_notification_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5693d80bea1da6676b9e3bfcbb"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "notification_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d699e517552244cc66b5d8cf2"`);
        await queryRunner.query(`DROP TABLE "user_notification_masters"`);
        await queryRunner.query(`DROP TYPE "public"."user_notification_masters_digest_frequency_enum"`);
        await queryRunner.query(`DROP TABLE "notification_variables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58e4a26add3dbc104fc9265d5a"`);
        await queryRunner.query(`DROP TABLE "notification_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33865415e76edbac9a8d01cd62"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36303b1a357c0ce359ea820dc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3829ae1a6554108530f1b56d74"`);
        await queryRunner.query(`DROP TABLE "company_notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."company_notification_templates_provider_enum"`);
        await queryRunner.query(`DROP TABLE "business_services"`);
        await queryRunner.query(`DROP TABLE "business_specializations"`);
        await queryRunner.query(`DROP TABLE "verification_codes"`);
        await queryRunner.query(`DROP TABLE "password_resets"`);
        await queryRunner.query(`DROP TABLE "user_tokens"`);
        await queryRunner.query(`DROP TABLE "form_template"`);
        await queryRunner.query(`DROP TABLE "form_template_version"`);
        await queryRunner.query(`DROP TABLE "form_field"`);
        await queryRunner.query(`DROP TABLE "business_form_field"`);
        await queryRunner.query(`DROP TABLE "business_form"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "onboardings"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TYPE "public"."companies_entity_type_enum"`);
        await queryRunner.query(`DROP TABLE "company_addons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359f971aa4b0ae502460f822ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf6897b3f7b2e6b712bdf01f29"`);
        await queryRunner.query(`DROP TABLE "addons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abc159b084b9d36de6bcabbfb8"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TABLE "company_address"`);
        await queryRunner.query(`DROP TABLE "location"`);
        await queryRunner.query(`DROP TYPE "public"."location_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_251a1a9999d8f1d33f1fa15698"`);
        await queryRunner.query(`DROP TABLE "trade"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9156af13862cf05a303701a72f"`);
        await queryRunner.query(`DROP TABLE "trade_groups"`);
        await queryRunner.query(`DROP TABLE "base_specializations"`);
        await queryRunner.query(`DROP TABLE "base_services"`);
        await queryRunner.query(`DROP TABLE "company_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c180c8aef03938b9a3470d398f"`);
        await queryRunner.query(`DROP TABLE "location_working_hours"`);
        await queryRunner.query(`DROP TYPE "public"."location_working_hours_day_enum"`);
        await queryRunner.query(`DROP TABLE "location_address"`);
    }

}
